#!/usr/bin/env bash
set -euo pipefail
CHROME_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ROOT="$(cd "$CHROME_DIR/.." && pwd)"
source "$ROOT/config.sh"
cat > "$CHROME_DIR/config.js" <<EOF
// Generated by scripts/build.sh — edit config.sh, then re-run
export const SERVER_URL = "$SERVER_URL";
EOF
echo "config.js updated → $SERVER_URL"
